#!/bin/sh

# 1st parameter is absolute path to component source directory
# 2nd parameter is absolute path to component build directory
# 3rd parameter is path to Python QA directory

# For OS/X
DYLD_LIBRARY_PATH=/home/chris/Desktop/gnuradio/gruel/src/lib/:/home/chris/Desktop/gnuradio/gruel/src/swig/.libs:$DYLD_LIBRARY_PATH
export DYLD_LIBRARY_PATH

# For Win32
PATH=/home/chris/Desktop/gnuradio/gruel/:/home/chris/Desktop/gnuradio/gruel/.libs:$PATH

../../../run_tests.sh \
    /home/chris/Desktop/gnuradio/gruel/src \
    /home/chris/Desktop/gnuradio/gruel/src \
    .
